#include <iostream>
using std::string;

// adding attributes
// all of the attributes are private by default
// all of these members here are private

// private: whatever is private will be hidden
// public: you will be able to access it outside of the class 
// protected: in-between private and public

class Employee {
// private:
// protected:
public:
    string Name;
    string Company;
    int Age;

    // creating a introducing function
    void IntroduceYourself() {
        std::cout << "Name - " << Name << std::endl;
        std::cout << "Company - " << Company << std::endl;
        std::cout << "Age - " << Age << std::endl;
    }
    
    // creating a contructor function

    // contructor: a contructor is a special type of method when invoked everytime an object of a class is created
    // default contructor: a contructor automatically generated by the complier

    // contructor rules:
    // the contructor does not have a return type 
    // the contructor must be public
    // the contructor matches the class name

    
    Employee(string name, string company, int age) {
        Name = name;
        Company = company;
        Age = age;
    }
};

// creating the variable type
int main() {

    // class   object
    // invoking the constructor fucntion Employee
    Employee employee1 = Employee("Andre", "Néo-Manhattan", 25);

    // invoking the introducing function
    employee1.IntroduceYourself();

    Employee employee2 = Employee("Nam", "Néo-Manhattan", 24);

    employee2.IntroduceYourself();
}
